apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kafka
  description: Kafka service
  tags:
    - firebird
    - utilities
spec:
  type: firebird-utility
  lifecycle: production
  owner: user:account/krish.mehta
