apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reservations
  description: Reservations service
  tags:
    - firebird
    - platform
spec:
  type: firebird-platform
  lifecycle: production
  owner: user:account/krish.mehta
