apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: saga-orchestration
  description: Saga Orchestration service
  tags:
    - firebird
    - platform
spec:
  type: firebird-platform
  lifecycle: production
  owner: user:account/krish.mehta
